# -*- coding: utf-8 -*-
"""assainment_12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nl1Cx1jLp8-Zzqr64rp7AA1EUDz4rOI
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn .linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

df=pd.read_csv("/content/12 assainment.zip")

df.head(1)

df.iloc[:,:2]
df[["text","label"]]

df=df[df["label"].isin(["FAKE","REAL"])].dropna(subset=["text"])

df.shape

df["label"].value_counts()

x_train,x_test,y_train,y_test=train_test_split(df["text"],df["label"],test_size=0.2,random_state=42)

tfidf=TfidfVectorizer(stop_words="english",max_df=0.7)
tfidf_train=tfidf.fit_transform(x_train)
tfidf_test=tfidf.transform(x_test)

tfidf_train.shape

"""#model_training"""

model=PassiveAggressiveClassifier(max_iter=50)
model.fit(tfidf_train,y_train)

y_pred=model.predict(tfidf_test)

y_pred

accuracy=accuracy_score(y_test,y_pred)

accuracy

cm=confusion_matrix(y_test,y_pred,labels=["FAKE","REAL"])
cm

new_news=["Scientists at NASA confirmed a new exoplanet discovery yesterday."]
v=tfidf.transform(new_news)
model.predict(v)

"""#next_steps"""

mdel=LogisticRegression(max_iter=1000)
mdel.fit(tfidf_train,y_train)

tfidf=TfidfVectorizer(stop_words="english",max_df=0.7)
tfidf_train=tfidf.fit_transform(x_train)
tfidf_test=tfidf.transform(x_test)



print(type(mdel))

y_pred=mdel.predict(tfidf_test)

accuracy=accuracy_score(y_test,y_pred)

accuracy

Cm=confusion_matrix(y_test,y_pred,labels=["FAKE","REAL"])

Cm