# -*- coding: utf-8 -*-
"""Copy of module_358.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y67ASTNx5c3zpRASe1fgEDczpDWhSzbR
"""

Create a class named Car with the attributes brand, model, and year. Include a constructor to initialize these values and a method display_info() to print all the car details. Then create an object of the Car class and display its details.

Question 2: Create three classes Animal, Mammal, and Dog where Animal has a method eat(), Mammal inherits from Animal and has a method walk(), and Dog inherits from Mammal and has a method bark(). Create an object of Dog and demonstrate all three methods. Also, create a class Calculator with an add() method that can take either two or three parameters, and then create a subclass AdvancedCalculator that overrides the add() method to add any number of parameters using variable-length arguments. Demonstrate both functionalities.

Question 3: Create a class BankAccount with a private attribute balance and provide methods deposit() and withdraw() to modify the balance safely so that the balance cannot be accessed directly. Then create two subclasses SavingsAccount and CurrentAccount, each having a method account_type() that prints its respective account type. Demonstrate polymorphism by calling account_type() from different account objects.

"""*QUESTION_01*"""

class Car:
  def __init__(self,brand,model,year):
     self.brand=brand
     self.model=model
     self.year=year
  def display_info(self):

        print(f"brand:{self.brand}")
        print(f"model:{self.model}")
        print(f"year:{self.year}")

my_car=Car("BMW","X5",2025)
my_car.display_info()

"""# *`*QUWSTION_2

### Inheritance
#
"""

class Animal:
  def eat(self):
      print("Animal is eating")

class Mammal(Animal):
  def walk(self):
      print("Mammal is walking")

class dog(Mammal):
  def bark(self):
      print("dog is barking")

dog1=dog()
dog1.eat()
dog1.walk()
dog1.bark()
print(" my dog  is very smart")

"""# method overriding


"""

class Calculator():
  def add(self,a,b,c=None):
      if c==None:
          return a+b
      else:
          return a+b+c

class AdvancedCalculator(Calculator):
  def add (self,*args):
    total=0
    for num in args:
        total+=num
    return total

calc=Calculator()
print(calc.add(2,3))

adv=AdvancedCalculator()
print("advanced:",adv.add(1,2,3,4,5,6,7,8,9))

"""# Encapsulationand Polymorphism

"""

class BankAccount:

  def __init__(self,balance):
     self.__balance=balance

def deposit(self,amount):
    self.__balance=self.__balance+ amount
    print(f"{amount}")

def withdraw(self,amount):
    if amount<=self.__balance:
       self.__balance=self.__balance-amount
       print(f"amount")
    else:
        print("Influation_balance")

def get_balance(self):
    return self.__balance

def account_type(self):
    print("this is a generic bank account")

class SavingsAccount(BankAccount):
  def account_type(self):
      print("this is a savings account")

class currentAccount(BankAccount):
  def account_type(self):
      print("this is a current account")

"""# polymorphism"""

acc1 = SavingsAccount(5000)
acc2 = CurrentAccount(10000)

accounts = [acc1, acc2] # 2টাকে এক লিস্টে রাখলাম

for acc in accounts:
    acc.account_type() # একই method, কিন্তু object ভেদে আলাদা কাজ করছে
    acc.deposit(1000)
    print("বর্তমান Balance:", acc.get_balance())
    print("---")