# -*- coding: utf-8 -*-
"""Ecomerce_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRegFiUQ2APWwZk90rwWv3S5qpgrK6x5
"""

import numpy as np
import pandas as pd

df=pd.read_csv("/content/new module aa.csv")

df

df.head()

df.shape
df.info()

"""# 4"""

print(df["age"].min())
print(df["age"].max())
print(df["age"].mean())

"""# 5"""

df["first"].value_counts().head(3)



df.columns

"""# 6"""

phone_count=(df["phone"].value_counts())
dupliactes=phone_count[phone_count==2]
print(dupliactes)
phone_number=dupliactes.index[0]
print(df[df["phone"]==phone_number][["first","last","email","phone"]])

"""# 7"""

print((df['profession']=="Structural Engineer").sum())

df.columns

"""# 8"""

result=df[(df['profession']=="Structural Engineer")&(df["gender"]=="Male")]
print(len(result))

"""# 9"""

reasult=df[(df["profession"]=="Structural Engineer")&(df["gender"]=="Female")&(df["province"]=="AB")]

print(reasult[["first","last","gender","profession","province"]])

df.columns

"""# 10"""

print(df["price(CAD)"].max())
print(df["price(CAD)"].min())
print(df["price(CAD)"].mean())

"""# 11"""

cast=df[df["price(CAD)"]==0]
print(cast[["first","last","email","price(CAD)"]])

"""# New Section

# 12
"""

cast=df[df["price(CAD)"]>=100]
print(len(cast))
print(cast[["first","last","email","price(CAD)"]])

df.columns

df["cc_no"]

"""## problem face this question

# 13 number is very defficult
"""

df["cc_no"]

ttt=df[df["cc_no"]==5020000000000230]
print(len(ttt))

df["cc_exp"]

df.info()

"""# 14"""

f=pd.to_datetime(df["cc_exp"],format="%y-%b")

cards_2019=df[f.dt.year==2019]
print(len(cards_2019))

e=df[df["cc_type"]=="Visa"].value_counts()
e

df.info()

"""# 15"""

print((df["cc_type"]=="Visa").sum())

df["price(CAD)"]

"""# 16"""

result=df[(df["price(CAD)"]==100)&(df["cc_type"]=="Visa")]

r=(result[["first","last","cc_type","price(CAD)"]])
r

"""#17"""

df["profession"].value_counts().head(2)

"""# 18"""

providers=df["email"].str.split("@").str[1]
p=(providers.value_counts().head(5))
p

"""# 19"""

edu=(df["email"].str.split("@").str[1]=="am.edu")
e=edu.sum()
e

"""# 20"""

w=df["weekday"].value_counts()
w