# -*- coding: utf-8 -*-
"""module 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FIeVejY0yQWFgUqEu3gXd-FrU3beA4Jh
"""

import matplotlib.pyplot as plt

import numpy as np
x=np.arange(0,10)
y=x*2
z=x**2

"""# task 1"""

fig=plt.figure()
ax=fig.add_axes([0,0,1,1])
ax.plot(x,y,label="y=2x")
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_title("Exercise 1:single Axes")
ax.legend()

"""#task 2"""

fig=plt.figure()
ax1=fig.add_axes([0,0,1,1])
ax2=fig.add_axes([0.15,0.55,0.25,0.25])
ax1.plot(x,z)
ax1.set_xlabel("x");ax1.set_ylabel("z")
ax1.set_title("Exercise 2:Two Axes")
ax2.plot(x,z,color="red")
ax2.set_xlim(1,2)
ax2.set_ylim(0,5)

fig,axes=plt.subplots(1,2,figsize=(8,3))
for ax in axes:
  ax.plot(x,y,color="green")
  ax.set_xlabel("x")
  ax.set_ylabel("y")
fig.suptitle("Exescise 3:subplots() with for loop")
fig.tight_layout()

"""# task 4

"""

fig,axes=plt.subplots(1,2,figsize=(8,3))
axes[0].plot(x,y,color="green")
axes[0].set_title("y=2x")
axes[1].plot(x,z,color="red")
axes[1].set_title("y=x^2")
fig.tight_layout()

"""# task 5"""

fig,axes=plt.subplots(1,3,figsize=(11,3))
axes[0].plot(x,y,color="red")
axes[1].plot(x,z,color="green")
axes[2].plot(x,y,color="blue")
for ax in axes:
  ax.set_label("x")
fig.tight_layout()

"""# task 6"""

fig,axes=plt.subplots(1,2,figsize=(3,4))
axes[0].plot(x,y,color="red")
axes[1].plot(x,y,color="green")
fig.tight_layout()

"""# task 7"""

fig,ax=plt.subplots()
ax.scatter(x,y,color="red")
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_title("Exercise 7:scatter plot")



