# -*- coding: utf-8 -*-
"""module 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cp7cdp2WRkBmeickJ5NQKoW-45v01aVW

### question 1
"""

items_bought=[1,2,2,3,42]
print(all(isinstance(x,int)
for x in items_bought))

import numpy as np
items_bought=[1,2,2,3,42]
arr=np.array(items_bought)
print(arr.dtype)

"""# question 2

"""

import numpy as np
from scipy import stats
data=[1,2,2,3,42]
mean_value=np.mean(data)
median_value=np.median(data)
mode_reasult=stats.mode(data,keepdims=True)
print("Mean:",mean_value)
print("Median:",median_value)
print("Mode:",mode_reasult)

"""### question 3"""

data_with_outlier=[1,2,2,3,43]
data_without_outlier=[1,2,2,3]
print(np.mean(data_with_outlier))
print(np.mean(data_without_outlier))
print(np.median(data_with_outlier))
print(np.median(data_without_outlier))

"""## question 4

"""

import numpy as np
minute_on_site=[5,10,15,20,25,30]
money_spent=[12,22,35,48,55,66]
correlation=np.corrcoef(minute_on_site,money_spent)[1,0]
print(round(correlation,2))

"""## question 5

"""

import numpy as np
from scipy import stats
mean=0
std=1
lower=mean-1*std
upper=mean+1*std
percentage=(stats.norm.cdf(upper)-stats.norm.cdf(lower))*100
print(round(percentage,2))

