# -*- coding: utf-8 -*-
"""module 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hszN0k_fHvvLk2OjoxQjnrFEtYXWLgcs
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

sns.set_style("white")

titanic=sns.load_dataset("titanic")
tips=sns.load_dataset("tips")
iris=sns.load_dataset("iris")

tips.head()

iris.head()

tips.head()

sns.jointplot(x="total_bill",y="tip",data=tips)

"""# Task 2"""

sns.jointplot(x="total_bill",y="tip",data=tips,kind="hex")

"""# task 3"""

sns.histplot(titanic["fare"],color="red",bins=30,kde=False)

"""# Task 4"""

sns.boxplot(x="class",y="age",data=titanic,palette="rainbow")

"""# task 5"""

titanic.head()

sns.jointplot(x="fare",y="age",data=titanic)

"""# task 6"""

titanic["sex"].value_counts()

sns.countplot(x="sex",data=titanic,hue="class")

sns.heatmap(titanic.corr(numeric_only=True),cmap="coolwarm")
plt.title("titanic.corr()")