# -*- coding: utf-8 -*-
"""module 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMTt4hWVdMRloDDyvTm__NpeulOIvoy-
"""



import numpy as np

list=[1,2,3,4,5]
arr=np.array(list)
print(arr)
print(type(arr))
print(arr.dtype)

arr=np.arange(6)
print(arr)

arr=np.zeros(5)
print(arr)

matrix=np.arange(1,10).reshape(3,3)
print(matrix)

arr=np.ones(6)
print(arr)

arr2=np.full(5,10)
print(arr2)

arr3=np.arange(52,100,2)
print(arr3)

arr4,step=np.linspace(0,1,10,retstep=True)
print(arr4)

arr6=np.arange(25)
print(arr6)

arr7=np.arange(25).reshape(5,5)
print(arr7)

arr7=np.arange(25)
arr7.shape=(5,5)
print(arr7)

matrix=np.eye(4)
print(matrix)

arr9=np.linspace(0,20,5)
print(arr9)

"""# linspace and arange diffarance

"""

a=np.arange(0,10,2)
print(a)

b=np.linspace(0,20,5)
print(b)

num=np.random.randint(1,100)
print(num)

matrix=np.random.rand(7,5)
print(matrix)

w=np.eye(4)
print(w)